### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by egibbm** [DataDog/dd-trace-java#1654]
We are seeing a lot of `ClassCastException` after using v0.56.0. This is not the case with v0.55.0.

Sample exceptions:
```
org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ClassCastException logging ReusableSimpleMessage: |origin| is null or empty java.lang.ClassCastException
org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ClassCastException logging ReusableSimpleMessage: java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to org.apache.logging.log4j.util.StringMap
```

### Version
dd-trace-agent release: 0.56.0

### system properties:

datadog.slf4j.simpleLogger.dateTimeFormat='[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'
datadog.slf4j.simpleLogger.log.org.datadog.jmxfetch=warn
datadog.slf4j.simpleLogger.showDateTime=true
dd.jmxfetch.enabled=true
dd.logs.injection=true

### Environment:

JVM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11, mixed mode)
Java: version 1.8.0_171, vendor Oracle Corporation

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by richardstartin** [comment]
This was fixed by #1647 which will be released soon. Apologies for the inconvenience.

**Comment by egibbm** [comment]
We are still seeing the (same?) issue with v0.57.0

```
WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ClassCastException logging ReusableParameterizedMessage: {}. endpoint={}, clientip={}, x_forwarded_for={}, userAgent={}. java.lang.ClassCastException: java.util.HashMap cannot be cast to org.apache.logging.log4j.util.StringMap
```

pls cmiiw.
