### ISSUE TITLE
Unable to use manual instrumentation using dd-trace-ot when also using dd-java-agent for continuous profiler

### ISSUE THREAD

**Issue by sriraamas** [DataDog/dd-trace-java#4507]
Hello,

We are experimenting with manual instrumentation and continuous profiler. We initialized a `DDTracer` in the application to use with manual instrumentation and used -javaagent argument to enable the profiler. I had to disable automatic instrumentation using dd.trace.enabled=false, but overriding the property during DDTracer initialization to enable manual instrumentation.

We are encountering an error in this setup when building a span and here is the most relevant part of the stack trace. We are using dd-trace-ot and dd-java-agent version 1.3.0 

```
java.lang.ClassCastException: class datadog.trace.bootstrap.instrumentation.api.UTF8BytesString cannot be cast to class ddtrot.dd.trace.bootstrap.instrumentation.api.UTF8BytesString (datadog.trace.bootstrap.instrumentation.api.UTF8BytesString is in unnamed module of loader 'bootstrap'; ddtrot.dd.trace.bootstrap.instrumentation.api.UTF8BytesString is in unnamed module of loader 'app')
        at ddtrot.dd.trace.core.DDSpanContext.<init>(DDSpanContext.java:187)
        at ddtrot.dd.trace.core.CoreTracer$CoreSpanBuilder.buildSpanContext(CoreTracer.java:1361)
        at ddtrot.dd.trace.core.CoreTracer$CoreSpanBuilder.buildSpan(CoreTracer.java:1132)
        at ddtrot.dd.trace.core.CoreTracer$CoreSpanBuilder.start(CoreTracer.java:1141)
        at datadog.opentracing.DDTracer$DDSpanBuilder.start(DDTracer.java:618)

```

Any help would be appreciated!

**Comment by bantonsson** [comment]
Hi @sriraamas, mixing `dd-trace-ot` with the java agent is not supported. One other way would be to use the OpenTracing automatic instrumentation of the java agent, while disabling all other integrations.

Maybe you could try only depending on `opentracing-api`, adding the Datadog java agent, and these settings `-Ddd.integrations.enabled=false -Ddd.trace.integration.opentracing.enabled=true`.

**Comment by gpoulin** [comment]
This was working fine before 1.X and we relying on that. We looked at enabling only the opentracing integration in the datadog agent, however we currently use a custom `ScopeManager` and some `TraceInterceptor`. How could we migrate those with using only the datadog java agent?

**Comment by bantonsson** [comment]
Hi @gpoulin, using `dd-trace-ot` with the Datadog Java agent has never been a supported combination. The `dd-trace-ot` dependency should only be used if you want to completely configure your own OpenTracing tracer using the underlying Datadog Tracer and not use any auto-instrumentation.

* If you want to use the OpenTracing API with the Datadog Java agent, you depend on `io.opentracing:opentracing-api`
* If you want to use the Datadog API with the Datadog Java agent you depend on `com.datadoghq:dd-trace-api`. 
* If you want to use both, you depend on both.

**Comment by gpoulin** [comment]
To be clear, we don't want to use the auto-instrumentation for tracing, however we still want to use DD java agent for the JVM metrics and the profiler. We also want to be able to have the same runtime-id in the trace and the metrics.

We are using Finagle as our main I/O framework which auto-instrumentation doesn't support. To overcome that, we implemented a custom ScopeManager to properly propagate SpanContext across threads. How would we inject this ScopeManager without using `dd-trace-ot`?

**Comment by mcculls** [comment]
FYI this [change](https://github.com/DataDog/dd-trace-java/pull/6005) should avoid the reported `ClassCastException` when attaching `dd-java-agent` and using `dd-trace-ot`

**Comment by bm1549** [comment]
I'm closing this issue out since it was fixed via #6005. Please re-open this issue if the issue re-occurs

**Comment by vbabenkoru** [comment]
It looks like #6005 got reverted, and this issue is still present.
